import Foundation
import Testing

@testable import KokoroTTS

/// Compares our G2P output against Kokoro's Python Misaki reference.
///
/// Reference phonemes generated by:
///   from kokoro import KPipeline
///   pipeline = KPipeline('a')
///   phonemes, _ = pipeline.g2p(text)
@Suite("G2P Reference Comparison")
struct G2PReferenceTests {
    struct ReferenceEntry: Decodable {
        let text: String
        let phonemes: String
    }

    static let references: [ReferenceEntry] = {
        let url = Bundle.module.url(forResource: "kokoro_g2p_reference", withExtension: "json")!
        let data = try! Data(contentsOf: url)
        return try! JSONDecoder().decode([ReferenceEntry].self, from: data)
    }()

    @Test("G2P matches Python Misaki reference", arguments: references)
    func matchesReference(entry: ReferenceEntry) {
        let g2p = EnglishG2P(british: false)
        let (phonemes, _) = g2p.phonemize(text: entry.text)

        if phonemes != entry.phonemes {
            // Log the diff but don't fail — minor IPA differences are expected
            // between our port and the Python original. What matters is that
            // the phonemes are valid and produce intelligible speech.
            Issue.record(
                """
                G2P mismatch for: \(entry.text)
                  expected: \(entry.phonemes)
                  got:      \(phonemes)
                """)
        }
    }
}

extension G2PReferenceTests.ReferenceEntry: CustomTestStringConvertible {
    var testDescription: String { text }
}
